import { logger } from '../utils/logger';

export interface TemplatePattern {
  timestamp: number;
  action: 'click' | 'use' | 'abandon';
  sessionId: string;
  context?: Record<string, unknown>;
}

export interface Template {
  id: string;
  label: string;
  prompt: string;
  color: string;
  icon: string;
  tags: string[];
  frequency: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  isAutoGenerated?: boolean;
  generatedAt?: number;
  generatedBy?: string;
  relevanceScore?: number;
}

export interface UserContext {
  currentModule: string;
  recentTopics: string[];
  activeTools: string[];
  timeOfDay: 'morning' | 'afternoon' | 'evening';
  device: 'mobile' | 'desktop';
  sessionId: string;
}

export interface RecommendedTemplate extends Template {
  relevanceScore: number;
  adaptation?: string;
}

export interface TemplateLearningState {
  userTemplates: Record<string, TemplatePatternStatistics>;
  generatedTemplates: Template[];
}

export interface TemplatePatternStatistics {
  templateId: string;
  totalUses: number;
  firstUse: number;
  lastUse: number;
  contexts: TemplatePattern[];
  generatedFromPatterns: TemplatePattern[];
  relevanceScore: number;
}

class TemplateLearningManager {
  private storageKey = 'gia-template-learning';

  private loadLearning(): TemplateLearningState {
    try {
      const stored = localStorage.getItem(this.storageKey);
      if (stored) {
        return JSON.parse(stored);
      }
    } catch (e) {
      logger.error('[TemplateLearning] Failed to load learning data:', e);
    }
    return { userTemplates: {}, generatedTemplates: [] };
  }

  private saveLearning(learning: TemplateLearningState): void {
    try {
      localStorage.setItem(this.storageKey, JSON.stringify(learning));
    } catch (e) {
      logger.error('[TemplateLearning] Failed to save learning data:', e);
    }
  }

  recordTemplateUse(templateId: string, context: Record<string, unknown>): void {
    const learning = this.loadLearning();

    if (!learning.userTemplates[templateId]) {
      learning.userTemplates[templateId] = {
        templateId,
        totalUses: 0,
        firstUse: Date.now(),
        lastUse: Date.now(),
        contexts: [],
        generatedFromPatterns: [],
        relevanceScore: 0.5
      };
    }

    const templateData = learning.userTemplates[templateId];
    templateData.totalUses++;
    templateData.lastUse = Date.now();
    templateData.contexts.push({
      timestamp: Date.now(),
      action: 'use',
      context,
      sessionId: `session-${Date.now()}`
    });

    templateData.relevanceScore = Math.min(1.0, templateData.relevanceScore + (0.1 / templateData.totalUses));

    this.saveLearning(learning);
    this.generateNewTemplatesFromPattern(templateId);
  }

  private generateNewTemplatesFromPattern(templateId: string): void {
    const learning = this.loadLearning();
    const templateData = learning.userTemplates[templateId];

    if (templateData.totalUses >= 3 && templateData.contexts.length > 3) {
      const suggestions = this.analyzeUsagePattern(templateData);
      suggestions.forEach(suggestion => {
        learning.generatedTemplates.push(suggestion);
      });
      this.saveLearning(learning);
    }
  }

  private analyzeUsagePattern(templateData: TemplatePatternStatistics): Template[] {
    const suggestions: Template[] = [];
    const useContexts = templateData.contexts.filter(c => c.action === 'use');

    if (useContexts.length < 3) return suggestions;

    const allText = useContexts.map(c => c.context).join(' ').toLowerCase();
    const commonTopics = this.extractCommonTopics(allText);

    const baseTemplates = [
      { label: `Based on your ${commonTopics[0]} usage`, prompt: `Help me with ${commonTopics[0] || 'related task'}`, tags: ['custom'] },
      { label: `Quick ${commonTopics[1] || 'action'}`, prompt: `Take swift action regarding ${commonTopics[1] || 'your request'}`, tags: ['quick', 'swift'] },
      { label: `Advanced ${commonTopics[2] || 'feature'}`, prompt: `Utilize advanced capabilities for ${commonTopics[2] || 'complex task'}`, tags: ['advanced', 'expert'] }
    ];

    baseTemplates.forEach((base, idx) => {
      const colors = ['#a855f7', '#3b82f6', '#10b981', '#f59e0b', '#ef4444'];
      const template: Template = {
        id: `generated-${Date.now()}-${idx}`, 
        label: base.label,
        prompt: base.prompt,
        color: colors[idx % colors.length],
        icon: 'sparkles',
        tags: base.tags.concat(commonTopics.slice(0, 2)),
        frequency: 0,
        difficulty: 'intermediate',
        isAutoGenerated: true,
        generatedAt: Date.now(),
        generatedBy: 'analyzeUsagePattern'
      };
      suggestions.push(template);
    });

    return suggestions;
  }

  private extractCommonTopics(text: string): string[] {
    const words = text
      .replace(/[^\p{L}\w\s]/gu, '')
      .split(/\s+/)
      .filter(word => word.length > 3 && !['the', 'and', 'for', 'with', 'this', 'that', 'were', 'from', 'they', 'have', 'been', 'will', 'your', 'can', 'use', 'help', 'more', 'than', 'also', 'any', 'its', 'new', 'time', 'know', 'just', 'like', 'look', 'want', 'make', 'good', 'need', 'out', 'see', 'way', 'how', 'get', 'do', 'if', 'my', 'one', 'all', 'our', 'up', 'so', 'us', 'as', 'is', 'be'].includes(word.toLowerCase()))
      .map(w => w.toLowerCase());

    return [...new Set(words.slice(0, 5))];
  }

  getAllTemplates(): Template[] {
    const learning = this.loadLearning();
    const globalTemplates = this.getGlobalTemplates();

    const withStats = globalTemplates.map(template => {
      const stats = learning.userTemplates[template.id];
      return stats
        ? { ...template, frequency: stats.totalUses, relevanceScore: stats.relevanceScore, isAutoGenerated: false }
        : template;
    });

    return [...withStats, ...learning.generatedTemplates];
  }

  getGlobalTemplates(): Template[] {
    return [
      { id: 'exam-prep', icon: 'graduation-cap', label: 'Exam Prep', prompt: 'Quiz me on WASSCE past questions for', color: '#a855f7', tags: ['study', 'test', 'revision'], frequency: 0, difficulty: 'intermediate' },
      { id: 'bece-prep', icon: 'book-open', label: 'BECE Prep', prompt: 'Help me study for BECE — topic:', color: '#3b82f6', tags: ['study', 'test', 'exam'], frequency: 0, difficulty: 'beginner' },
      { id: 'code-help', icon: 'code', label: 'Code Help', prompt: 'Explain and fix this code:', color: '#ec4899', tags: ['debug', 'code', 'fix'], frequency: 0, difficulty: 'intermediate' },
      { id: 'summarize-url', icon: 'link', label: 'Summarize URL', prompt: 'Summarize this URL: https://', color: '#10b981', tags: ['web', 'research', 'content'], frequency: 0, difficulty: 'beginner' },
      { id: 'plan-week', icon: 'calendar', label: 'Plan My Week', prompt: 'Help me plan my study week. My exams are:', color: '#f59e0b', tags: ['productivity', 'planning', 'schedule'], frequency: 0, difficulty: 'intermediate' },
      { id: 'code-debug', icon: 'bug', label: 'Code Debug', prompt: 'Debug this code and explain the issues:', color: '#ef4444', tags: ['debug', 'code', 'fix'], frequency: 0, difficulty: 'intermediate' },
      { id: 'refactor-code', icon: 'git-branch', label: 'Refactor Code', prompt: 'Refactor this code for better performance:', color: '#f97316', tags: ['performance', 'optimization', 'code'], frequency: 0, difficulty: 'advanced' },
      { id: 'ts-quickstart', icon: 'file-code', label: 'TypeScript Quick Start', prompt: 'Create a TypeScript file with interfaces for:', color: '#0ea5e9', tags: ['typescript', 'types', 'interfaces'], frequency: 0, difficulty: 'beginner' },
      { id: 'git-workflow', icon: 'git-branch', label: 'Git Workflow', prompt: 'Explain git best practices for:', color: '#10b981', tags: ['git', 'version-control', 'workflow'], frequency: 0, difficulty: 'intermediate' },
      { id: 'auto-responder', icon: 'zap', label: 'Auto-Responder Setup', prompt: 'Create an automated response for recurring user queries like:', color: '#22c55e', tags: ['automation', 'responses', 'workflow'], frequency: 0, difficulty: 'intermediate' }
    ];
  }
}

export const templateLearning = new TemplateLearningManager();
